name: Build Applications

on:
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  build_applications:
    name: ${{ matrix.os }} with ${{ matrix.specfile }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        specfile: [glue_app_bundle.spec]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pyinstaller
      run: pip install git+https://github.com/pyinstaller/pyinstaller
    - name: Install glue
      run: pip install glueviz PyQt5==5.11.3
    - name: Run pyinstaller
      run: pyinstaller ${{ matrix.specfile }}
    - name: Remove unused directory
      run: rm -rf dist/start_glue
    #- name: Fix MacOS X application
    #  run: python fix_osx.py dist/glue.app
    - name: Create DMG
      run: hdiutil create -volname "Glue" -srcfolder dist -ov -format UDZO glue.dmg
    - name: Install awscli
      run: pip install awscli
    - name: Upload to S3
      run: aws s3 cp glue.dmg s3://glue-installers-exp/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
