name: Build Applications

on:
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  build_applications:
    name: ${{ matrix.os }}
    runs-on: ubuntu-18.04
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install library dependencies
      run: yum install -y devtoolset-10-dyninst
    - name: Install Python dependencies
      run: /opt/python/cp37-cp37m/bin/python -m pip install -r requirements.txt
    - name: Run pyinstaller
      run: /opt/python/cp37-cp37m/bin/pyinstaller glue_app.spec
    - name: Prepare application for distribution
      shell: bash
      run: ./prepare_"$RUNNER_OS".sh ${GITHUB_REF##*/}
    - name: Output list of included packages
      if: matrix.os == 'ubuntu-18.04'
      run: /opt/python/cp37-cp37m/bin/pyinstaller -m pip freeze > included-packages.txt
    - name: Install awscli
      run: /opt/python/cp37-cp37m/bin/pyinstaller -m pip install awscli
    - name: Upload glue to S3
      shell: bash
      if: github.event_name != 'pull_request'
      run: /opt/python/cp37-cp37m/bin/aws s3 cp glue* s3://glueviz/installers/${GITHUB_REF##*/}/
      working-directory: dist
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload package list to S3
      if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-18.04'
      run: /opt/python/cp37-cp37m/bin/aws s3 cp included-packages.txt s3://glueviz/installers/${GITHUB_REF##*/}/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
