name: Build Applications

on:
  push:
    branches:
    - '*'
    tags:
    - '*'

jobs:
  build_applications:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:

    - name: Checkout code
      uses: actions/checkout@v2



    - name: Install apt dependencies
      run: sudo apt-get install -y gir1.2-gtk-3.0 python3-devel python3-pyqt5 python3-pyqt5.qtwebengine python3-pip python3-setuptools python3-wheel
    - name: Install Python dependencies
      run: python3 -m pip install -r requirements.txt
    - name: Run pyinstaller
      run: pyinstaller glue_app.spec
    - name: Uninstall lxml
      run: python3 -m pip uninstall -y lxml
    - name: Prepare application for distribution
      shell: bash
      run: ./prepare_"$RUNNER_OS".sh ${GITHUB_REF##*/}
    - name: Output list of included packages
      if: matrix.os == 'ubuntu-18.04'
      run: python3 -m pip freeze > included-packages.txt
    - name: Install awscli
      run: python3 -m pip install awscli
    - name: Upload glue to S3
      shell: bash
      if: github.event_name != 'pull_request'
      run: aws s3 cp glue* s3://glueviz/installers/${GITHUB_REF##*/}/
      working-directory: dist
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Upload package list to S3
      if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-18.04'
      run: aws s3 cp included-packages.txt s3://glueviz/installers/${GITHUB_REF##*/}/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
