name: Build Applications

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  build_applications:
    name: ${{ matrix.os }} with ${{ matrix.specfile }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        specfile: [glue_app_bundle.spec]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pyinstaller
      run: pip install pyinstaller
    - name: Install glue
      run: pip install glueviz PyQt5
    - name: Run pyinstaller
      run: pyinstaller ${{ matrix.specfile }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}_${{ matrix.specfile }}
        path: dist
